			<h4>The SNiPA development team</h4>
			<p>
				SNiPA is a joint project of the <a href="http://www.helmholtz-muenchen.de/en/ibis/" target="_blank">Institute of Bioinformatics and Systems Biology</a> (IBIS) at the  <a href="http://www.helmholtz-muenchen.de" target="_blank">Helmholtz Zentrum M&uuml;nchen</a> and the <a href="http://qatar-weill.cornell.edu/research/faculty/suhreLab.html" target="_blank">Bioinformatics Core Facility</a> at the <a href="http://qatar-weill.cornell.edu" target="_blank">Weill Cornell Medical College in Qatar</a>.<br /><br />
				SNiPA was mainly developed and is being maintained by <a href="http://www.helmholtz-muenchen.de/en/ibis/institute/groups/metabolomics/staff/staff/ma/2403/index.html" target="_blank">Matthias Arnold</a> and <a href="http://www.helmholtz-muenchen.de/en/ibis/institute/groups/metabolomics/staff/staff/ma/709/index.html" target="_blank">Johannes Raffler</a>, both members of the IBIS <a href="http://metabolomics.helmholtz-muenchen.de" target="_blank">Metabolomics group</a>.				
			</p>
			<h4>Contact us</h4>
			<p>If you have any questions regarding SNiPA, feel free to contact us: <a href="mailto:feedback@snipa.org">feedback@snipa.org</a></p>
			<h4>Citing SNiPA</h4>
				<p>Arnold M<sup>&Dagger;</sup>, Raffler J<sup>&Dagger;</sup>, Pfeufer A, Suhre K, and Kastenm&uuml;ller G. SNiPA: an interactive, genetic variant-centered annotation browser. Bioinformatics (2014). Available at http://www.snipa.org. Accessed [date of access].
				 <br/><span style="font-size: smaller;"><sup>&Dagger;</sup>These authors contributed equally.</span>
				</p>
					
			<h4>Acknowledgements</h4>
			<p>We thank all research groups that generated the data integrated into SNiPA (see the <a href="?task=documentation">documentation</a> for a full list of references).<br />
			Also, we thank the developers of <a href="http://www.broadinstitute.org/mpg/snap/" target="_blank">SNAP at the Broad Institute</a> for their inspiring work. We hope that they will find our tool just as useful as SNAP has been to us in the past.</p>
			</p>
			
			<h4>Legal Notices</h4>
			<p><b><i>Disclaimer</i></b> <span style="font-size: smaller;">(adapted from <a href="http://www.ensembl.org/info/about/legal/index.html" target="_blank">Ensembl</a>)</span></p>
			<p>SNiPA imposes no restrictions on access to, or use of, the data provided and the software used to analyse and present it. SNiPA data generated by members of the project are available without restriction.<br/><br/>Some of the data and software included in the distribution may be subject to third-party constraints. Users of the data and software are solely responsible for establishing the nature of and complying with any such restrictions. The Helmholtz Zentrum München (GmbH) and the Weill Cornell Medical College in Qatar provide this data and software in good faith, but make no warranty, express or implied, nor assume any legal liability or responsibility for any purpose for which they are used.</p>
